---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myzmqserver
  labels:
    app: myzmqserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myzmqserver
  template:
    metadata:
      labels:
        app: myzmqserver
    spec:
      containers:
      - name: myzmqserver
        image: hfarkhari/client_server_zmq:server_5.0
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: myzmqserver-service
  labels:
    app: myzmqserver
spec:
  selector:
    app: myzmqserver
  type: NodePort
  ports:
  - port: 5555
#    nodePort: 31000
    targetPort: 5555
    protocol: TCP
    name: http

    
